In [10]:
import warnings
warnings.simplefilter('ignore')
import requests
import json
from pprint import pprint
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt

In [2]:
filePath = "Gen1_List.csv"
gen1List = pd.read_csv(filePath)
gen1List

,Number,Name,Types,Type1,Type2,Height(m),Weight(kg),Male_Pct,Female_Pct,Capt_Rate,...,Poison_Dmg,Ground_Dmg,Flying_Dmg,Psychic_Dmg,Bug_Dmg,Rock_Dmg,Ghost_Dmg,Dragon_Dmg,Evolutions,Legendary
0,1,Bulbasaur,2,grass,poison,0.7,6.9,87.5,12.5,45,...,1.0,1.0,2.0,2.0,4.0,1.0,1,1,2,0
1,2,Ivysaur,2,grass,poison,1.0,13.0,87.5,12.5,45,...,1.0,1.0,2.0,2.0,4.0,1.0,1,1,2,0
2,3,Venusaur,2,grass,poison,2.0,100.0,87.5,12.5,45,...,1.0,1.0,2.0,2.0,4.0,1.0,1,1,2,0
3,4,Charmander,1,fire,None,0.6,8.5,87.5,12.5,45,...,1.0,2.0,1.0,1.0,0.5,2.0,1,1,2,0
4,5,Charmeleon,1,fire,None,1.1,19.0,87.5,12.5,45,...,1.0,2.0,1.0,1.0,0.5,2.0,1,1,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
146,147,Dratini,1,dragon,None,1.8,3.3,50.0,50.0,45,...,1.0,1.0,1.0,1.0,1.0,1.0,1,2,2,0
147,148,Dragonair,1,dragon,None,4.0,16.5,50.0,50.0,45,...,1.0,1.0,1.0,1.0,1.0,1.0,1,2,2,0
148,149,Dragonite,2,dragon,flying,2.2,210.0,50.0,50.0,45,...,1.0,0.0,1.0,1.0,0.5,2.0,1,2,2,0
149,150,Mewtwo,1,psychic,None,2.0,122.0,0.0,0.0,3,...,1.0,1.0,1.0,0.5,2.0,1.0,0,1,0,1
150,151,Mew,1,psychic,None,0.4,4.0,0.0,0.0,45,...,1.0,1.0,1.0,0.5,2.0,1.0,0,1,0,1

In [9]:
print(gen1List[" Type1"].unique())

['grass' 'fire' 'water' 'bug' 'normal' 'poison' 'electric' 'ground'
 'fighting' 'psychic' 'rock' 'ghost' 'ice' 'dragon']

In [26]:
for i in np.arange(0, len(gen1List[" Type1"])):
    if gen1List[" Type1"][i] == "grass":
        gen1List[" Type1"][i] = 1
    elif gen1List[" Type1"][i] == "fire":
        gen1List[" Type1"][i] = 2
    elif gen1List[" Type1"][i] == "water":
        gen1List[" Type1"][i] = 3
    elif gen1List[" Type1"][i] == "bug":
        gen1List[" Type1"][i] = 4
    elif gen1List[" Type1"][i] == "normal":
        gen1List[" Type1"][i] = 5
    elif gen1List[" Type1"][i] == "poison":
        gen1List[" Type1"][i] = 6
    elif gen1List[" Type1"][i] == "electric":
        gen1List[" Type1"][i] = 7
    elif gen1List[" Type1"][i] == "ground":
        gen1List[" Type1"][i] = 8
    elif gen1List[" Type1"][i] == "fighting":
        gen1List[" Type1"][i] = 9
    elif gen1List[" Type1"][i] == "psychic":
        gen1List[" Type1"][i] = 10
    elif gen1List[" Type1"][i] == "rock":
        gen1List[" Type1"][i] = 11
    elif gen1List[" Type1"][i] == "ghost":
        gen1List[" Type1"][i] = 12
    elif gen1List[" Type1"][i] == "ice":
        gen1List[" Type1"][i] = 13
    elif gen1List[" Type1"][i] == "dragon":
        gen1List[" Type1"][i] = 14

<ipython-input-26-e570d9782030>:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  gen1List[" Type1"][i] = 10

In [27]:
gen1List[" Type1"]

0       1
1       1
2       1
3       2
4       2
       ..
146    14
147    14
148    14
149    10
150    10
Name:  Type1, Length: 151, dtype: object

In [ ]:
# for x = 0 in gen1List[" Type1"]:
#     if x = "grass":
#         gen1List[" Type1"][x]
#     else if x = "fire":
#         x = 2
#     else if x = "water":

In [28]:
X = gen1List[[" HP", " Attack", " Defense", " Special", " Speed"]]
# HP, Attack, Defense, Special, Speed
y = gen1List[" Type1"].values.reshape(-1, 1)
print(X.shape, y.shape)

(151, 5) (151, 1)

In [29]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 42)
X_train.head()

      HP   Attack   Defense   Special   Speed
105   50      120        53        35      87
4     58       64        58        65      80
32    61       72        57        55      65
42    45       50        55        75      30
144   90       90        85       125     100

In [30]:
from sklearn.preprocessing import StandardScaler
X_scaler = StandardScaler().fit(X_train)
y_scaler = StandardScaler().fit(y_train)

X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)
y_train_scaled = y_scaler.transform(y_train)
y_test_scaled = y_scaler.transform(y_test)

In [16]:
model = LinearRegression()
print(model)

LinearRegression()

In [17]:
X = gen1List.iloc[:, 5].values.reshape(-1, 1)  # values converts it into a numpy array
Y = gen1List.iloc[:, 6].values.reshape(-1, 1)  # -1 means that calculate the dimension of rows, but have 1 column

In [18]:
model.fit(X, Y)
print(model)

LinearRegression()

In [19]:
print('Weight coefficients: ', model.coef_)
print('y-axis intercept: ', model.intercept_)

Weight coefficients:  [[35.03611383]]
y-axis intercept:  [4.09394083]